### ISSUE TITLE
Index Out Of Range Exception

### ISSUE THREAD

**Issue by raitonoberu** [raitonoberu/ytmusic#1]
When searching, very rarely, the parser will throw an "index out of range exception" depending on what is being searched. Here's an example:

```
package main

import "github.com/raitonoberu/ytmusic"

func main() {
	srch := ytmusic.Search("panama")
	srch.Next()
}
```

*Originally reported by @thenhawke [here](https://github.com/raitonoberu/ytsearch/issues/4)*

**Comment by raitonoberu** [comment]
Stacktrace:
```
panic: runtime error: index out of range [4] with length 3

goroutine 1 [running]:
github.com/raitonoberu/ytmusic.getValue({0xee4680, 0xc000005ce0}, {0xc0000cba28, 0x6, 0x38})
        C:/Users/raitonoberu/go/pkg/mod/github.com/raitonoberu/ytmusic@v0.0.0-20210902101119-7ce669c8bf47/parsers.go:19 +0x19c
github.com/raitonoberu/ytmusic.parsePlaylistItem({0xef3340, 0xc000347890})
        C:/Users/raitonoberu/go/pkg/mod/github.com/raitonoberu/ytmusic@v0.0.0-20210902101119-7ce669c8bf47/parsers.go:377 +0x3e6      
github.com/raitonoberu/ytmusic.parseShelf({0xef3340, 0xc000334360})
        C:/Users/raitonoberu/go/pkg/mod/github.com/raitonoberu/ytmusic@v0.0.0-20210902101119-7ce669c8bf47/parsers.go:173 +0xb47      
github.com/raitonoberu/ytmusic.parseSearchPage({0xef3340, 0xc00001d2c0})
        C:/Users/raitonoberu/go/pkg/mod/github.com/raitonoberu/ytmusic@v0.0.0-20210902101119-7ce669c8bf47/parsers.go:57 +0x2a8
github.com/raitonoberu/ytmusic.(*SearchClient).Next(0xc0000cbf18)
        C:/Users/raitonoberu/go/pkg/mod/github.com/raitonoberu/ytmusic@v0.0.0-20210902101119-7ce669c8bf47/search.go:68 +0x6f
main.main()
        C:/Users/raitonoberu/Desktop/New Folder/main.go:9 +0x58
exit status 2
```

**Comment by raitonoberu** [comment]
Fixed in https://github.com/raitonoberu/ytmusic/commit/6fb8e797c7b2724e3def8ef3422c9c1a1e431b1b.

The problem was caused by playlists with no information about the number of tracks and a poorly written `getValue` function that did not check whether the index exceeds the length of the list.

Thanks for reporting.
